CREATE TABLE worker
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(1000)                                  NOT NUlL CHECK (LENGTH(NAME) BETWEEN 2 AND 1000),
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL    ENUM ('Trainee', 'Junior', 'Middle', 'Senior') NOT NULL,
    SALARY   INT CHECK (SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE client
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NUlL CHECK (LENGTH(NAME) BETWEEN 2 AND 1000)
);

CREATE TABLE project
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID   INT REFERENCES client (ID),
    START_DATE  DATE,
    FINISH_DATE DATE
);

CREATE TABLE project_worker
(
    PROJECT_ID INT REFERENCES project (ID),
    WORKER_ID  INT REFERENCES worker (ID),
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);