SELECT 'YOUNGEST' TYPE, NAME, BIRTHDAY FROM worker
WHERE BIRTHDAY =
      (SELECT MIN(BIRTHDAY) FROM worker)
UNION
SELECT 'ELDEST' TYPE, NAME, BIRTHDAY FROM worker
WHERE BIRTHDAY =
      (SELECT MAX(BIRTHDAY) FROM worker);