SELECT ID, DATEDIFF(MONTH, START_DATE, FINISH_DATE) AS MONTH_COUNT
FROM project p
WHERE DATEDIFF(MONTH, START_DATE, FINISH_DATE) =
       (SELECT MAX(x.count)
        FROM (SELECT DATEDIFF(MONTH, START_DATE, FINISH_DATE) count
              FROM project p) x)
